# Generated by Django 5.1.6 on 2025-02-17 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0005_medico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField()),
                ('descricao', models.CharField(max_length=300)),
                ('id_medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alunos.medico')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alunos.paciente')),
            ],
        ),
    ]
